<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVy49jgi\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVy49jgi/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVy49jgi.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVy49jgi\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerVy49jgi\appDevDebugProjectContainer([
    'container.build_hash' => 'Vy49jgi',
    'container.build_id' => '54474649',
    'container.build_time' => 1665736153,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVy49jgi');
